name: Container-image
on: [push]
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bwolf/cert-manager-webhook-gandi/cert-manager-webhook-gandi
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
        registry: docker.pkg.github.com
        buildoptions: "--compress --force-rm"
